### ISSUE TITLE
Passing username and password

### ISSUE THREAD

**Issue by amjad** [remkade/multisite-json-api#1]
Hi, 

I'm trying to pass my username and password in the header but I keep getting this error: 

```
{
    "id": 403,
    "message": "Invalid Username or Password",
    "url": "http://github.com/remkade/multisite-json-api/wiki"
}
```

**Comment by amjad** [comment]
I found the issue. You have not written the correct variable in your README. It should be:

HTTP Headers **User and Password** respectively. (not Username)

**Comment by ScreamingHawk** [comment]
Fixed in my pull request #2

**Comment by amjad** [comment]
👍🏻

**Comment by remkade** [comment]
Referenced PR had been merged.
