### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by mariano** [remkade/multisite-json-api#3]
Hey @remkade I was wondering if this project was abandoned.

I am looking to introduce some extra functionality and doing some general fixes, so if you feel like you don't have the time to maintain it anymore (I've been there), I can fork it.

Thanks for the awesome work btw

**Comment by remkade** [comment]
I haven't really had the chance to do much with it in a long time. Feel free to fork, I can add a link to your fork in the read me if you like.
